#ifndef _LIBFIXMATH_CONF_H
#define _LIBFIXMATH_CONF_H


// #define FIXMATH_NO_64BIT
// #define FIXMATH_OPTIMIZE_8BIT
#define FIXMATH_NO_CACHE
//#define FIXMATH_NO_OVERFLOW
#define FIXMATH_NO_ROUNDING
//#define FIXMATH_FAST_SIN
//#define FIXMATH_SIN_LUT


#endif
